disabled_rules:
    - trailing_whitespace
    - file_length
    
opt_in_rules:
    - empty_string

excluded:
    - Pods
    - KCS/Application
    - KCSUnitTest

line_length: 140
cyclomatic_complexity: 20
identifier_name:
    max_length: 50
