# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

use_frameworks!

target 'KCS' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for KCS
   
  pod 'RxSwift', '6.6.0'
  pod 'RxCocoa', '6.6.0'
  pod 'RxGesture'
  pod 'Alamofire'
  pod 'SwiftLint'
  pod 'NMapsMap'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'RxKeyboard'

post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end

end

target 'KCSUnitTest' do

  pod 'RxTest'
  pod 'RxBlocking'

end
