name: test-ci

# 트리거 조건 (push 하거나 PR 하면 하단의 jobs를 실행하겠다는 뜻)
on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop
      

# 트리거 발생 시 실행할 작업들 
jobs:
  test:  
    runs-on: macos-13  # iOS 플랫폼에서 실행

    steps:
      #Select your required version
      - name: Select Xcode 15.1
        run: sudo xcode-select -s /Applications/Xcode_15.1.app/Contents/Developer

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy secrets to github action
        env:
          ENV: ${{ secrets.ENV }}  # repository secrets 에서 가져옴
          OCCUPY_SECRET_DIR: ./KCS  # 레포지토리 내 파일 의 위치
          OCCUPY_SECRET_DIR_FILE_NAME: Secret.xcconfig  # 파일 이름

        # secrets 값 복사
        run: |
          echo $ENV >> $OCCUPY_SECRET_DIR/$OCCUPY_SECRET_DIR_FILE_NAME

      - name: Install Gems
        if: steps.cache_gems.outputs.cache-hit != 'true'
        run: bundle install --jobs 4 --retry 3

      - name: Install Pods Release
        if: steps.cache_pods.outputs.cache-hit != 'true'
        run: bundle exec pod install --repo-update

      - name: Run tests
        run: bundle exec fastlane test