name: test-ci

# 트리거 조건 (push 하거나 PR 하면 하단의 jobs를 실행하겠다는 뜻)
on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop
      

# 트리거 발생 시 실행할 작업들 
jobs:
  test:  
    runs-on: macos-latest  # iOS 플랫폼에서 실행

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy secrets to github action
        env:
          ENV: ${{ secrets.ENV }}  # repository secrets 에서 가져옴
          OCCUPY_SECRET_DIR: ./KCS  # 레포지토리 내 파일 의 위치
          OCCUPY_SECRET_DIR_FILE_NAME: Secret.xcconfig  # 파일 이름

        # secrets 값 복사
        run: |
          echo $ENV >> $OCCUPY_SECRET_DIR/$OCCUPY_SECRET_DIR_FILE_NAME
      
      - name: Set up Xcode
        uses: actions/setup-xcode@v3
        with:
          xcode-version: '15'
      
      # CocoaPod 을 사용하므로 설치후 테스트 진행
      - name: Install CocoaPods
        run: |
          pod install --repo-update --clean-install --project-directory=KCS

      - name: Build and test
        run: |          
          xcodebuild clean test -workspace KCS/KCS.xcworkspace \
          -scheme KCS \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2'
          # ❗-project 옵션으로 scheme 설정
          # ❗-destination 옵션으로 OS 버전이 설정
